/**
 * GENERATED by `scripts/build-record-types.mjs`. Do not edit.
 *
 * Every class spec says holds record data, with the JSON name spec publishes
 * for it. Derived from `src/spec/`, which is itself built from the checkout —
 * so nothing here is transcribed and a change upstream arrives as a build
 * diff rather than as a silent disagreement.
 *
 * The population is spec's own rule: an `rdfs:subClassOf` chain reaching
 * `prov:Entity` or `prov:Activity`. The twelve classes it does not yet reach
 * are declared in `src/record-types/pending-spec-50.json` with the issue that
 * deletes them.
 *
 * @module record-types
 */

/** One class spec declares as holding record data. */
export interface DerivedClass {
  /** The class IRI. */
  readonly iri: string;
  /** The JSON name spec publishes, or the local name where it publishes none. */
  readonly name: string;
  /** The local name, always. */
  readonly localName: string;
  /** Deprecated class IRIs that `rdfs:seeAlso` says this one superseded. */
  readonly supersedes: readonly string[];
}

export const DERIVED_CLASSES: readonly DerivedClass[] = [
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#ActivityData",
    "name": "ActivityData",
    "localName": "ActivityData",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#ActivitySnapshot",
    "name": "ActivitySnapshot",
    "localName": "ActivitySnapshot",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#AdvisoryApplicationActivity",
    "name": "AdvisoryApplicationActivity",
    "localName": "AdvisoryApplicationActivity",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#AIDiscardedExtraction",
    "name": "AIDiscardedExtraction",
    "localName": "AIDiscardedExtraction",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#AIExtractionActivity",
    "name": "AIExtractionActivity",
    "localName": "AIExtractionActivity",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#AIGenerationActivity",
    "name": "AIGenerationActivity",
    "localName": "AIGenerationActivity",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#AllergyRecord",
    "name": "AllergyRecord",
    "localName": "AllergyRecord",
    "supersedes": [
      "https://ns.cascadeprotocol.org/clinical/v1#Allergy"
    ]
  },
  {
    "iri": "https://ns.cascadeprotocol.org/coverage/v1#AppealRecord",
    "name": "AppealRecord",
    "localName": "AppealRecord",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#Attachment",
    "name": "Attachment",
    "localName": "Attachment",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#AttentionItem",
    "name": "AttentionItem",
    "localName": "AttentionItem",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/coverage/v1#BenefitStatement",
    "name": "BenefitStatement",
    "localName": "BenefitStatement",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#BloodPressureData",
    "name": "BloodPressureData",
    "localName": "BloodPressureData",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#BodyMeasurements",
    "name": "BodyMeasurements",
    "localName": "BodyMeasurements",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#BPStatistics",
    "name": "BPStatistics",
    "localName": "BPStatistics",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#CheckInSettings",
    "name": "CheckInSettings",
    "localName": "CheckInSettings",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/coverage/v1#ClaimRecord",
    "name": "ClaimRecord",
    "localName": "ClaimRecord",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#ClinicalDocument",
    "name": "ClinicalDocument",
    "localName": "ClinicalDocument",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#ConditionRecord",
    "name": "ConditionRecord",
    "localName": "ConditionRecord",
    "supersedes": [
      "https://ns.cascadeprotocol.org/clinical/v1#Condition"
    ]
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#ConflictDetail",
    "name": "ConflictDetail",
    "localName": "ConflictDetail",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#ConsultationNote",
    "name": "ConsultationNote",
    "localName": "ConsultationNote",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/coverage/v1#CopaySchedule",
    "name": "CopaySchedule",
    "localName": "CopaySchedule",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#CorrelationInsight",
    "name": "CorrelationInsight",
    "localName": "CorrelationInsight",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#DailyActivitySnapshot",
    "name": "DailyActivitySnapshot",
    "localName": "DailyActivitySnapshot",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#DailyCheckIn",
    "name": "DailyCheckIn",
    "localName": "DailyCheckIn",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#DailySleepSnapshot",
    "name": "DailySleepSnapshot",
    "localName": "DailySleepSnapshot",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/coverage/v1#Deductible",
    "name": "Deductible",
    "localName": "Deductible",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/coverage/v1#DenialNotice",
    "name": "DenialNotice",
    "localName": "DenialNotice",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#DischargeSummary",
    "name": "DischargeSummary",
    "localName": "DischargeSummary",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#DiscussionTopic",
    "name": "DiscussionTopic",
    "localName": "DiscussionTopic",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#Encounter",
    "name": "Encounter",
    "localName": "Encounter",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#EncounterParticipant",
    "name": "EncounterParticipant",
    "localName": "EncounterParticipant",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#ExportManifest",
    "name": "ExportManifest",
    "localName": "ExportManifest",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#FamilyHistoryRecord",
    "name": "FamilyHistoryRecord",
    "localName": "FamilyHistoryRecord",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#HealthProfile",
    "name": "HealthProfile",
    "localName": "HealthProfile",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#HeartRateData",
    "name": "HeartRateData",
    "localName": "HeartRateData",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#HRVData",
    "name": "HRVData",
    "localName": "HRVData",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#HRVStatistics",
    "name": "HRVStatistics",
    "localName": "HRVStatistics",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#ImagingReport",
    "name": "ImagingReport",
    "localName": "ImagingReport",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#ImagingStudy",
    "name": "ImagingStudy",
    "localName": "ImagingStudy",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#ImmunizationRecord",
    "name": "ImmunizationRecord",
    "localName": "ImmunizationRecord",
    "supersedes": [
      "https://ns.cascadeprotocol.org/clinical/v1#Immunization"
    ]
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#ImmunizationSummary",
    "name": "ImmunizationSummary",
    "localName": "ImmunizationSummary",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#ImplantedDevice",
    "name": "ImplantedDevice",
    "localName": "ImplantedDevice",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/coverage/v1#InsurancePlan",
    "name": "InsurancePlan",
    "localName": "InsurancePlan",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#IntakeQuestionnaireResponse",
    "name": "IntakeQuestionnaireResponse",
    "localName": "IntakeQuestionnaireResponse",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#InteractionScenario",
    "name": "InteractionScenario",
    "localName": "InteractionScenario",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#KeyIndicator",
    "name": "KeyIndicator",
    "localName": "KeyIndicator",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#LaboratoryReport",
    "name": "LaboratoryReport",
    "localName": "LaboratoryReport",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#LabResultRecord",
    "name": "LabResultRecord",
    "localName": "LabResultRecord",
    "supersedes": [
      "https://ns.cascadeprotocol.org/clinical/v1#LabResult"
    ]
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#LabResultSummary",
    "name": "LabResultSummary",
    "localName": "LabResultSummary",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#LabTestSeries",
    "name": "LabTestSeries",
    "localName": "LabTestSeries",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#Medication",
    "name": "Medication",
    "localName": "Medication",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#MedicationAdministration",
    "name": "MedicationAdministration",
    "localName": "MedicationAdministration",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#MedicationChangeRecord",
    "name": "MedicationChangeRecord",
    "localName": "MedicationChangeRecord",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#MedicationUseEpisode",
    "name": "MedicationUseEpisode",
    "localName": "MedicationUseEpisode",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#MetricTrend",
    "name": "MetricTrend",
    "localName": "MetricTrend",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#PatientProfile",
    "name": "PatientProfile",
    "localName": "PatientProfile",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/pots/v1#POTSCheckResult",
    "name": "POTSCheckResult",
    "localName": "POTSCheckResult",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#Procedure",
    "name": "Procedure",
    "localName": "Procedure",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#ProcedureSummary",
    "name": "ProcedureSummary",
    "localName": "ProcedureSummary",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#ProgressNote",
    "name": "ProgressNote",
    "localName": "ProgressNote",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#ProxyAgent",
    "name": "ProxyAgent",
    "localName": "ProxyAgent",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#RecordSummary",
    "name": "RecordSummary",
    "localName": "RecordSummary",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#ResponseItem",
    "name": "ResponseItem",
    "localName": "ResponseItem",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#SelfReport",
    "name": "SelfReport",
    "localName": "SelfReport",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#SleepData",
    "name": "SleepData",
    "localName": "SleepData",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#SleepSnapshot",
    "name": "SleepSnapshot",
    "localName": "SleepSnapshot",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/core/v1#SocialHistoryConsent",
    "name": "SocialHistoryConsent",
    "localName": "SocialHistoryConsent",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#SocialHistoryRecord",
    "name": "SocialHistoryRecord",
    "localName": "SocialHistoryRecord",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#SocialHistoryRecord",
    "name": "SocialHistoryRecord",
    "localName": "SocialHistoryRecord",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#Supplement",
    "name": "Supplement",
    "localName": "Supplement",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#TrendInsight",
    "name": "TrendInsight",
    "localName": "TrendInsight",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#VisitPrepSummary",
    "name": "VisitPrepSummary",
    "localName": "VisitPrepSummary",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#VisitPrepTray",
    "name": "VisitPrepTray",
    "localName": "VisitPrepTray",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#VisitSummary",
    "name": "VisitSummary",
    "localName": "VisitSummary",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#VisitTrayItem",
    "name": "VisitTrayItem",
    "localName": "VisitTrayItem",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/clinical/v1#VitalSign",
    "name": "VitalSign",
    "localName": "VitalSign",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/health/v1#VO2MaxStatistics",
    "name": "VO2MaxStatistics",
    "localName": "VO2MaxStatistics",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#WellnessProfileReference",
    "name": "WellnessProfileReference",
    "localName": "WellnessProfileReference",
    "supersedes": []
  },
  {
    "iri": "https://ns.cascadeprotocol.org/checkup/v1#WellnessSummary",
    "name": "WellnessSummary",
    "localName": "WellnessSummary",
    "supersedes": []
  }
] as const;
