/**
 * `scripts/copy-spec-data.mjs` carries the spec DATA into `dist/spec/` and
 * leaves the build's diagnostics behind.
 *
 * NOTHING GENERATED BY THE DIAGNOSTICS BUILD SHIPS. `src/spec/diagnostics/*.json`,
 * `src/spec/diagnostics.json` and `src/spec/diagnostics.md` are the build's
 * report on spec — a worklist for the people fixing spec and this SDK — and
 * the copy script's rule is "every `.json`/`.jsonld` under `src/spec/`", which
 * would carry the two JSON forms into `dist/` and, through `package.json`'s
 * `files`, into the tarball. This says the exclusion holds, by running the
 * script against a scratch `src/spec/` that has both kinds of file.
 *
 * Run as a real child process, the way `copy-vendor.test.ts` does: the
 * script resolves `src/spec` and `dist/spec` against its working directory,
 * so a scratch directory is the whole fixture.
 *
 * @module tests/scripts
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, it, expect, afterEach } from 'vitest';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SCRIPT = resolve(root, 'scripts/copy-spec-data.mjs');

let workdir: string | undefined;

afterEach(() => {
  if (workdir) rmSync(workdir, { recursive: true, force: true });
  workdir = undefined;
});

/** A scratch working directory holding `src/spec/` with the files given. */
function scratchTree(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'copy-spec-data-test-'));
  for (const [file, content] of Object.entries(files)) {
    mkdirSync(dirname(join(dir, file)), { recursive: true });
    writeFileSync(join(dir, file), content, 'utf-8');
  }
  return dir;
}

describe('copy-spec-data.mjs', () => {
  it('copies the data and skips everything under src/spec/diagnostics*', () => {
    workdir = scratchTree({
      'src/spec/ontologies/core.jsonld': '[]',
      'src/spec/ontologies/PROVENANCE.json': '{"commit":null}',
      'src/spec/contexts/core.jsonld': '{"@context":{}}',
      'src/spec/diagnostics/build-terms.json': '[]',
      'src/spec/diagnostics/build-record-types.json': '[]',
      'src/spec/diagnostics/build-spec-data.json': '[]',
      'src/spec/diagnostics.json': '{"commit":null,"findings":[]}',
      'src/spec/diagnostics.md': '# nothing',
    });

    execFileSync('node', [SCRIPT], { cwd: workdir, stdio: 'pipe' });

    expect(existsSync(join(workdir, 'dist/spec/ontologies/core.jsonld'))).toBe(true);
    expect(existsSync(join(workdir, 'dist/spec/ontologies/PROVENANCE.json'))).toBe(true);
    expect(existsSync(join(workdir, 'dist/spec/contexts/core.jsonld'))).toBe(true);

    expect(existsSync(join(workdir, 'dist/spec/diagnostics')), 'the per-generator findings shipped').toBe(false);
    expect(existsSync(join(workdir, 'dist/spec/diagnostics.json')), 'the merged findings shipped').toBe(false);
    expect(existsSync(join(workdir, 'dist/spec/diagnostics.md')), 'the rendered findings shipped').toBe(false);
  });
});
